custom:
  rabbit-mq:
    queue: email-registration
spring:
  #RabbitMQ
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    virtual-host: /
  #Mail
  mail:
    username: spring.boot.programming@gmail.com
    host: smtp.gmail.com
    port: 587
    password: zdmf aowk vpzo nxnb
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            required: true
            enable: true
        debug: false

# Eureka
eureka:
  preferIdAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8072/eureka/