spring:
  mail:
    username:
    host: smtp.gmail.com
    port: 587
    password:
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            required: true
            enable: true
        debug: true

