server:
  port: 9000

spring:
  application:
    name: email
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8071/"

#Config Eureka
#Allow disabled server by call api actuator/shutdown with method post
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
endpoints:
  shutdown:
    enabled: true
info:
  app:
    name: "email"
    description: "Shopee be email demo"
    version: "1.0.0"

