#Config Eureka
#Allow disabled server by call api actuator/shutdown with method post
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
endpoints:
  shutdown:
    enabled: true
info:
  app:
    name: "email"
    description: "Shopee be email demo"
    version: "1.0.0"

custom:
  rabbit-mq:
    queue: email-registration
spring:
  #RabbitMQ
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    virtual-host: /
  #Mail
  mail:
    username:
    host: smtp.gmail.com
    port: 587
    password:
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            required: true
            enable: true
        debug: true
  cloud:
    function:
      definition: email|sms
    stream:
      bindings:
        emailsms-in-0:
          destination: send-communication
          group: ${spring.application.name}
        emailsms-out-0:
          destination: communication-sent

# Eureka
eureka:
  preferIdAddress: false
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8072/eureka/

